-Added Image to assets folder "amanoEvercold.jpg" and put into hierarchy
-Text changed so it now reads "this text has been changed"
-Created "ImageRot.cs" script that rotates the image every frame
-Created new branch Lab3Rebase and rebased with Lab3BranchHP
